In [2]:
import pandas as pd
import numpy as np

In [5]:
flight_data = pd.read_csv('./flight_data_2024.csv')
flight_data.head()

/var/folders/jh/2z6063n91jn5nsq56zvsxlhw0000gn/T/ipykernel_6683/289479383.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  flight_data = pd.read_csv('./flight_data_2024.csv')

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,1,1,1,2024-01-01,9E,4814.0,JFK,"New York, NY",New York,...,0,136.0,122.0,84.0,509.0,0,0,0,0,0
1,2024,1,1,1,2024-01-01,9E,4815.0,MSP,"Minneapolis, MN",Minnesota,...,0,130.0,114.0,88.0,622.0,0,0,0,0,0
2,2024,1,1,1,2024-01-01,9E,4817.0,JFK,"New York, NY",New York,...,0,106.0,90.0,61.0,288.0,0,0,0,0,0
3,2024,1,1,1,2024-01-01,9E,4817.0,RIC,"Richmond, VA",Virginia,...,0,111.0,76.0,51.0,288.0,0,0,0,0,0
4,2024,1,1,1,2024-01-01,9E,4818.0,DTW,"Detroit, MI",Michigan,...,0,79.0,70.0,45.0,237.0,0,0,0,0,0

In [6]:
flight_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7079081 entries, 0 to 7079080
Data columns (total 35 columns):
 #   Column               Dtype
---  ------               -----
 0   year                 int64
 1   month                int64
 2   day_of_month         int64
 3   day_of_week          int64
 4   fl_date              object
 5   op_unique_carrier    object
 6   op_carrier_fl_num    float64
 7   origin               object
 8   origin_city_name     object
 9   origin_state_nm      object
 10  dest                 object
 11  dest_city_name       object
 12  dest_state_nm        object
 13  crs_dep_time         int64
 14  dep_time             float64
 15  dep_delay            float64
 16  taxi_out             float64
 17  wheels_off           float64
 18  wheels_on            float64
 19  taxi_in              float64
 20  crs_arr_time         int64
 21  arr_time             float64
 22  arr_delay            float64
 23  cancelled            int64
 24  cancellation_code    object
 25  diverted             int64
 26  crs_elapsed_time     float64
 27  actual_elapsed_time  float64
 28  air_time             float64
 29  distance             float64
 30  carrier_delay        int64
 31  weather_delay        int64
 32  nas_delay            int64
 33  security_delay       int64
 34  late_aircraft_delay  int64
dtypes: float64(13), int64(13), object(9)
memory usage: 1.8+ GB

In [7]:
flight_data.isna().sum()

year                         0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
op_unique_carrier            0
op_carrier_fl_num            1
origin                       0
origin_city_name             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_nm                0
crs_dep_time                 0
dep_time                 92659
dep_delay                92970
taxi_out                 95734
wheels_off               95734
wheels_on                97856
taxi_in                  97856
crs_arr_time                 0
arr_time                 97854
arr_delay               113814
cancelled                    0
cancellation_code      6982766
diverted                     0
crs_elapsed_time             1
actual_elapsed_time     113814
air_time                113814
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [8]:
flight_data.drop(columns=['cancellation_code'], inplace=True)
# REmove 'taxi_out', 'wheels_off',  'wheels_on', 'taxi_in'
flight_data.drop(columns=['taxi_out', 'wheels_off',  'wheels_on', 'taxi_in'], inplace=True)
# Remove origin, dest
flight_data.drop(columns=['origin', 'dest'], inplace=True)
# Remove diverted and distance column
flight_data.drop(columns=['diverted', 'distance'], inplace=True)

In [9]:
flight_data.dropna(inplace=True)

In [10]:
flight_data.isna().sum()

year                   0
month                  0
day_of_month           0
day_of_week            0
fl_date                0
op_unique_carrier      0
op_carrier_fl_num      0
origin_city_name       0
origin_state_nm        0
dest_city_name         0
dest_state_nm          0
crs_dep_time           0
dep_time               0
dep_delay              0
crs_arr_time           0
arr_time               0
arr_delay              0
cancelled              0
crs_elapsed_time       0
actual_elapsed_time    0
air_time               0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [11]:
flight_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6965266 entries, 0 to 7079080
Data columns (total 26 columns):
 #   Column               Dtype
---  ------               -----
 0   year                 int64
 1   month                int64
 2   day_of_month         int64
 3   day_of_week          int64
 4   fl_date              object
 5   op_unique_carrier    object
 6   op_carrier_fl_num    float64
 7   origin_city_name     object
 8   origin_state_nm      object
 9   dest_city_name       object
 10  dest_state_nm        object
 11  crs_dep_time         int64
 12  dep_time             float64
 13  dep_delay            float64
 14  crs_arr_time         int64
 15  arr_time             float64
 16  arr_delay            float64
 17  cancelled            int64
 18  crs_elapsed_time     float64
 19  actual_elapsed_time  float64
 20  air_time             float64
 21  carrier_delay        int64
 22  weather_delay        int64
 23  nas_delay            int64
 24  security_delay       int64
 25  late_aircraft_delay  int64
dtypes: float64(8), int64(12), object(6)
memory usage: 1.4+ GB

In [12]:
sampled_df = (
    flight_data
    .groupby('month', group_keys=False)
    .apply(lambda x: x.sample(frac=0.2, random_state=42))
)

sampled_df = sampled_df.reset_index(drop=True)

In [13]:
sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1393053 entries, 0 to 1393052
Data columns (total 26 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   year                 1393053 non-null  int64
 1   month                1393053 non-null  int64
 2   day_of_month         1393053 non-null  int64
 3   day_of_week          1393053 non-null  int64
 4   fl_date              1393053 non-null  object
 5   op_unique_carrier    1393053 non-null  object
 6   op_carrier_fl_num    1393053 non-null  float64
 7   origin_city_name     1393053 non-null  object
 8   origin_state_nm      1393053 non-null  object
 9   dest_city_name       1393053 non-null  object
 10  dest_state_nm        1393053 non-null  object
 11  crs_dep_time         1393053 non-null  int64
 12  dep_time             1393053 non-null  float64
 13  dep_delay            1393053 non-null  float64
 14  crs_arr_time         1393053 non-null  int64
 15  arr_time             1393053 non-null  float64
 16  arr_delay            1393053 non-null  float64
 17  cancelled            1393053 non-null  int64
 18  crs_elapsed_time     1393053 non-null  float64
 19  actual_elapsed_time  1393053 non-null  float64
 20  air_time             1393053 non-null  float64
 21  carrier_delay        1393053 non-null  int64
 22  weather_delay        1393053 non-null  int64
 23  nas_delay            1393053 non-null  int64
 24  security_delay       1393053 non-null  int64
 25  late_aircraft_delay  1393053 non-null  int64
dtypes: float64(8), int64(12), object(6)
memory usage: 276.3+ MB

In [14]:
sampled_df.head()

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin_city_name,origin_state_nm,dest_city_name,...,arr_delay,cancelled,crs_elapsed_time,actual_elapsed_time,air_time,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,1,4,4,2024-01-04,WN,673.0,"Kansas City, MO",Missouri,"Milwaukee, WI",...,-15.0,0,95.0,85.0,68.0,0,0,0,0,0
1,2024,1,21,7,2024-01-21,OO,5458.0,"Chicago, IL",Illinois,"Sioux Falls, SD",...,12.0,0,120.0,120.0,72.0,0,0,0,0,0
2,2024,1,26,5,2024-01-26,WN,636.0,"Kansas City, MO",Missouri,"Austin, TX",...,0.0,0,120.0,117.0,107.0,0,0,0,0,0
3,2024,1,22,1,2024-01-22,MQ,3805.0,"Dallas/Fort Worth, TX",Texas,"Corpus Christi, TX",...,3.0,0,86.0,91.0,67.0,0,0,0,0,0
4,2024,1,7,7,2024-01-07,WN,433.0,"Orlando, FL",Florida,"Dallas, TX",...,5.0,0,175.0,171.0,154.0,0,0,0,0,0

In [15]:
flight_data['month'].value_counts(normalize=True)

month
7     0.088143
10    0.087364
8     0.086759
6     0.086324
5     0.086031
3     0.084047
12    0.083964
9     0.083021
4     0.082830
11    0.082112
1     0.075427
2     0.073977
Name: proportion, dtype: float64

In [16]:
sampled_df['month'].value_counts(normalize=True)

month
7     0.088143
10    0.087364
8     0.086759
6     0.086324
5     0.086030
3     0.084048
12    0.083964
9     0.083021
4     0.082830
11    0.082112
1     0.075427
2     0.073977
Name: proportion, dtype: float64

In [18]:
# Save as csv flight_data_sample.csv
sampled_df.to_csv('./flight_data_sample.csv', index=False)